[package]
name = "oargs"
description = "A simple log output system written in Rust"
version = "0.1.0"
authors = ["Ouki76"]
repository = "https://github.com/Ouki76/oargs"
readme = "README.md"
license = "MIT"
license-file = "LICENSE"
edition = "2021"